name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Esto quita el aviso naranja de Node 20 deprecado
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # 1. LE DECIMOS DONDE TRABAJAR:
    defaults:
      run:
        working-directory: proyectoFinal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' 
          cache: 'npm'
          # 2. RUTA AL LOCK FILE:
          cache-dependency-path: 'proyectoFinal/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          NODE_ENV: test
          # 3. SECRETOS: Asegúrate de tener MONGO_URL en GitHub Secrets
          MONGO_URL: mongodb+srv://hugogalb9595_db_user:ShgYxqdnqOPhn3RL@cluster0.ok5hgzh.mongodb.net/ecommerce?retryWrites=true&w=majority