name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Si tus tests de Jest necesitan una base de datos real y no usas mocks
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          NODE_ENV: test
          # Aquí pasas la URL de tu base de datos si es necesaria
          MONGO_URL: mongodb://localhost:27017/testdb